# Generated by Django 3.1 on 2020-08-18 02:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_auto_20200817_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='authorized',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_authorized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
