# Generated by Django 3.1 on 2020-08-16 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_auto_20200816_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroompermission',
            name='public_key',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='chatroom',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='chat.chatroom'),
        ),
    ]
