# Generated by Django 3.1 on 2020-08-16 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20200816_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroompermission',
            name='public_key',
        ),
    ]
