# Generated by Django 3.1 on 2020-08-16 02:05

from django.db import migrations, models
import userLogin.models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='myuser',
            managers=[
                ('objects', userLogin.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
